#################### Deployment ###################
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front-container
        image: registry.gitlab.com/gitlabodix/cvtheque-front-prod
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: gitlab-secrets-front-prod
#################### Service ####################    
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
    